### ISSUE TITLE
[Feature Request] Resource: {url_template}

### ISSUE THREAD

**Issue by maykar** [mad-ady/home-assistant-customizations#1]
This might be a big ask as I know this isn't supported in the vanilla HA restful sensor, but it would be amazing to be able to use a template as an URL in your modified jsonrest sensor .

**Comment by mad-ady** [comment]
I'm not sure what you're trying to do - can you show me an example?

I'm not using the jsonrest component anymore - what I was trying to do has
been eventually migrated in a different form in the rest component. For
example:
```
  - platform: rest
    resource: !secret samygo_tv_living_channelinfo
    method: GET
    name: TV Living ChannelInfo
    json_attributes:
      - source
      - pvr_status
      - power_state
      - tv_mode
```
Are you trying to read resource from a template?
